import '@/styles/globals.css'
import DefaultLayout from '@/components/Layouts/DefaultLayout'
import { Provider } from 'react-redux'
import Head from 'next/head'
import store from '@/store/index'
import { appWithI18Next } from 'ni18n'
import { ni18nConfig } from 'ni18n.config'

const App = ({ Component, pageProps }) => {
    const getLayout = Component.getLayout ?? ((page) => <DefaultLayout>{page}</DefaultLayout>)
    return (
        <Provider store={store}>
            <Head>
                <title>VRISTO - Multipurpose Tailwind Dashboard Template</title>
                <meta charSet="UTF-8" />
                <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            {getLayout(<Component {...pageProps} />)}
        </Provider>
    )
}

export default appWithI18Next(App, ni18nConfig)
